# .github/workflows/ci.yml
name: Invoice Payment CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Basic syntax & security checks
        run: |
          pip install flake8 bandit
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          bandit -r . || true

      - name: Verify Streamlit app builds
        run: |
          python -m py_compile app.py

      - name: Finish
        run: echo "✅ CI checks completed successfully!"
